<?php

namespace EZ\CoreBundle\Repository;

/**
 * JsonapiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JsonapiRepository extends \Doctrine\ORM\EntityRepository
{
}
