ez_support:
    resource: "@EZSupportBundle/Resources/config/routing.yml"
    prefix:   /

ez_faq:
    resource: "@EZFAQBundle/Resources/config/routing.yml"
    prefix:   /

ez_article:
    resource: "@EZArticleBundle/Resources/config/routing.yml"
    prefix:   /

ez_user:
    resource: "@EZUserBundle/Resources/config/routing.yml"
    prefix:   /

ez_core:
    resource: "@EZCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"