# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    core:
        class: EZ\CoreBundle\Core\Core
        arguments: ['@jsonapi']

    jsonapi:
        class: EZ\CoreBundle\JSONAPI\JSONAPI
        arguments: ['@doctrine.orm.entity_manager']
