admin:
    name: Support
    path: ez_support_admin
    icon: fa fa-life-ring
    display : true
default:
    display: true
    0:
        name: Rediger un ticket
        path: 'ez_support_new'
    1:
        name: Consulter mes tickets
        path: 'ez_support_list'
    name: Support
    path: '#'
