ez_support_new:
    path:     /support/new
    defaults: { _controller: EZSupportBundle:Default:new }
ez_support_admin:
    path:    /admin/support
    defaults: {_controller: EZSupportBundle:Admin:index}
ez_support_list:
    path:    /ticket/{id}
    defaults:
             _controller: EZSupportBundle:Default:list
             id: 0
ez_support_response:
    path:    /ticket/{id}/edit
    defaults: {_controller: EZSupportBundle:Default:newResponse}
ez_support_close:
    path:    /ticket/{id}/close
    defaults: {_controller: EZSupportBundle:Default:close}
#Recupération pseudo
ez_support_ajax_joueur:
    path:    /ajax/getplayers
    defaults: {_controller: EZSupportBundle:Xhr:getPlayers}
