<?php

namespace EZ\SupportBundle\Repository;

/**
 * Support_reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Support_reponseRepository extends \Doctrine\ORM\EntityRepository
{
}
