<?php

namespace EZ\SupportBundle\Repository;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends \Doctrine\ORM\EntityRepository
{
        public function getTicketsByUser($user)
        {
            $query = $this->createQueryBuilder('s')
                ->where('s.userId = :user')
                ->setParameter(':user',$user)
                ->orderBy('s.updateDate', 'DESC');
            return $query->getQuery()->getResult();
        }
}
