parameters:
    server_name: ExtazCMS
    server_ip: 5.196.182.62
    server_port: 24812
    info_site_url: www.extaz-cms.fr
    template: red
    icons: { twitter: { name: Twitter, link: null, icon: 'fa fa-twitter' }, facebook: { name: Facebook, link: 'facebook', icon: 'fa fa-facebook' }, youtube: { name: Youtube, link: null, icon: 'fa fa-youtube-play' }, Discord: { name: Discord, icon: ICON, link: www.discord.fr } }
    presentation: Bonjour
    email_contact: venard.paul@gmail.com
