parameters:
    jsonapi: { jsonapi_ip: vps02.spaceblock.fr, jsonapi_port: '20059', jsonapi_username: admin, jsonapi_password: changeme, jsonapi_salt: null }
    server_name:
    server_ip:
    server_port:
    info_site_url:
    template: red
