parameters:
    jsonapi: { jsonapi_ip: vps02.spaceblock.fr, jsonapi_port: '20059', jsonapi_username: admin, jsonapi_password: changeme, jsonapi_salt: null }
    server_name: test
    server_ip: 123.fr
    server_port: 2645
    info_site_url: www.test.com
    template: red
