ez_core_homepage:
    path:     /
    defaults: { _controller: EZCoreBundle:Main:index }

ez_core_admin:
    path:     /admin/
    defaults: { _controller: EZCoreBundle:Admin:index }

ez_core_template:
    path:     /admin/template
    defaults: { _controller: EZCoreBundle:Template:template }

ez_core_template_select:
    path:     /admin/template/{name}
    defaults: { _controller: EZCoreBundle:Template:select }

ez_core_jsonapi:
    path:     /admin/jsonapi
    defaults: { _controller: EZCoreBundle:Jsonapi:index }

ez_core_jsonapi_delete:
    path:     /admin/jsonapi/delete/{id}
    requirements:
        id : \d{1,}
    defaults: { _controller: EZCoreBundle:Jsonapi:delete }

ez_core_configuration:
    path:     /admin/configuration
    defaults: { _controller: EZCoreBundle:Configuration:index }

ez_core_social_network:
    path:     /admin/social
    defaults: { _controller: EZCoreBundle:SocialNetwork:index }

ajax_server_info:
    path:     /admin/jsonapi/info/{server_position}
    defaults: { _controller: EZCoreBundle:Jsonapi:serverInfo }
    options:
        expose: true

