ez_core_homepage:
    path:     /
    defaults: { _controller: EZCoreBundle:Main:index }

ez_core_admin:
    path:     /admin
    defaults: { _controller: EZCoreBundle:Admin:index }

ez_core_template:
    path:     /admin/template
    defaults: { _controller: EZCoreBundle:Template:template }

ez_core_template_select:
    path:     /admin/template/{name}
    defaults: { _controller: EZCoreBundle:Template:select }

ez_core_jsonapi:
    path:     /admin/jsonapi
    defaults: { _controller: EZCoreBundle:Jsonapi:index }
