ez_core_homepage:
    path:     /
    defaults: { _controller: EZCoreBundle:Main:index }


ez_core_admin:
    path:     /admin/
    defaults: { _controller: EZCoreBundle:Admin:index }

ez_core_server:
    path:     /admin/server
    defaults: { _controller: EZCoreBundle:Server:index }

ez_core_jsonapi:
    path:     /admin/jsonapi
    defaults: { _controller: EZCoreBundle:Jsonapi:index }

ez_core_jsonapi_delete:
    path:     /admin/jsonapi/delete/{id}
    requirements:
        id : \d{1,}
    defaults: { _controller: EZCoreBundle:Jsonapi:delete }

ez_core_configuration:
    path:     /admin/configuration
    defaults: { _controller: EZCoreBundle:Configuration:index }

ez_core_social_network:
    path:     /admin/social
    defaults: { _controller: EZCoreBundle:SocialNetwork:index }

ajax_server_info:
    path:     /admin/jsonapi/info/{server_position}
    defaults: { _controller: EZCoreBundle:Jsonapi:serverInfo }
    schemes:  [http]
    options:
        expose: true


reglement_ajax_form:
    path:     /admin/configuration/form/reglement
    defaults: { _controller: EZCoreBundle:Configuration:reglementAjaxForm }
    schemes:  [http]
    options:
        expose: true

social_ajax_form:
    path:     /admin/configuration/form/social
    defaults: { _controller: EZCoreBundle:Configuration:socialNetworkAjaxForm }
    schemes:  [http]
    options:
        expose: true

legal_ajax_form:
    path:     /admin/configuration/form/local
    defaults: { _controller: EZCoreBundle:Configuration:legalAjaxForm }
    schemes:  [http]
    options:
        expose: true



