admin:
    name: Utilisateurs
    path: ez_article_admin_list
    icon: fa fa-user-o
    display : true

default:
    display: false
#    name:
#    path:
#    0:
#         name:
#         path:
#    1:
#         name:
#         path: