#FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: EZ\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:  true
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"