fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

ez_user_admin_list:
    path:   /admin/users
    defaults: { _controller: EZUserBundle:User:index }

ez_user_admin_add:
    path:   /admin/adduser
    defaults: { _controller: EZUserBundle:User:add }

ez_user_admin_edit:
    path:   /admin/user/{id}
    defaults: { _controller: EZUserBundle:User:edit }

ez_user_edit:
    path:   /profile
    defaults: { _controller: EZUserBundle:User:userEdit }

