admin:
    name: Articles
    path: "#"
    icon: fa fa-book
    display : true
    0:
        name: Créer
        path: "#"
    1:
        name: Liste
        path: "#"

default:
    display: true
    name: Articles
    path: "#"