admin:
    name: Articles
    path: "#"
    icon: fa fa-book
    display : true
    0:
        name: Créer
        path: ez_article_admin_create
    1:
        name: Liste
        path: ez_article_admin_list

default:
    display: true
    name: Articles
    path: 'ez_article_homepage'
